import type { ApiIR, ProjectIR, QueryParamIR } from '../ir/ir.js';
import { queryFnName } from '../utils/names.js';

function zodExpr(p: QueryParamIR): string {
    let expr: string;
    switch (p.type) {
        case 'int': expr = 'z.coerce.number().int()'; break;
        case 'float': case 'decimal': expr = 'z.coerce.number()'; break;
        case 'boolean': expr = 'z.coerce.boolean()'; break;
        default: expr = 'z.string()';
    }
    if (p.default !== undefined) {
        const v = typeof p.default === 'string' ? JSON.stringify(p.default) : String(p.default);
        expr += `.default(${v})`;
    } else if (p.optional) {
        expr += '.optional()';
    }
    return expr;
}

/** "/api/products" -> "src/app/api/products/route.ts" */
export function apiFilePath(api: ApiIR): string {
    const segments = api.path.replace(/^\//, '').split('/');
    return `src/app/${segments.join('/')}/route.ts`;
}

export function generateRouteHandler(ir: ProjectIR, api: ApiIR): string {
    const fn = queryFnName(api.method, api.path);
    const hasQuery = api.query.length > 0;

    const zodSchema = hasQuery
        ? `const QuerySchema = z.object({
  ${api.query.map(p => `${p.name}: ${zodExpr(p)}`).join(',\n  ')}
});\n\n`
        : '';

    // auth lowering: non-public endpoints get an explicit guard stub that
    // fails closed (401) until a real auth provider is wired in.
    const authGuard = api.auth === 'public'
        ? ''
        : `  // auth: ${api.auth} - replace this stub with your auth provider check
  if (!request.headers.get('authorization')) {
    return Response.json({ error: 'unauthorized' }, { status: 401 });
  }
`;

    const parseQuery = hasQuery
        ? `  const { searchParams } = new URL(request.url);
  const parsed = QuerySchema.safeParse(Object.fromEntries(searchParams.entries()));
  if (!parsed.success) {
    return Response.json({ error: 'invalid query', issues: parsed.error.issues }, { status: 400 });
  }
  const items = await ${fn}(parsed.data);
`
        : `  const items = await ${fn}({});
`;

    return `// Generated by vibe-lang from \`api ${api.method} "${api.path}"\`. DO NOT EDIT.
${hasQuery ? `import { z } from 'zod';\n` : ''}import { ${fn} } from '@/lib/queries';

${zodSchema}export async function ${api.method}(request: Request) {
${authGuard}${parseQuery}  return Response.json(items);
}
`;
}
