import type { ChangeIR } from '../ir/change-ir.js';

/** Machine-readable plan consumed by the verifier and any AI executor. */
export function generatePlanJson(ir: ChangeIR): string {
    return JSON.stringify({ version: '0.1', kind: 'vibe-change-plan', plan: ir }, null, 2) + '\n';
}

/**
 * Deterministic executor prompt: every section is derived 1:1 from the
 * ChangeIR, so the same Vibefile always produces the same instructions.
 * This is the contract handed to an AI coding agent.
 */
export function generateAgentPrompt(ir: ChangeIR): string {
    const lines: string[] = [];
    lines.push(`# Change: ${ir.title}`);
    lines.push('');
    lines.push(`## Goal`);
    lines.push(ir.goal);
    lines.push('');
    lines.push('## File scope (HARD BOUNDARY)');
    lines.push('You may ONLY create or modify files matching these patterns:');
    for (const p of ir.scope.allow) lines.push(`- ALLOW \`${p}\``);
    if (ir.scope.forbid.length) {
        lines.push('');
        lines.push('You must NEVER touch files matching these patterns, even if it seems helpful:');
        for (const p of ir.scope.forbid) lines.push(`- FORBID \`${p}\``);
    }
    lines.push('');
    lines.push('If the task appears to require editing a file outside the allowed scope, STOP and report it instead of editing.');
    lines.push('');
    lines.push('## Requirements');
    for (const r of ir.requirements) lines.push(`- [${r.kind}] ${r.text}`);
    if (ir.styleHints.length) {
        lines.push('');
        lines.push('## Style');
        for (const s of ir.styleHints) lines.push(`- ${s}`);
    }
    if (ir.constraints.length) {
        lines.push('');
        lines.push('## Constraints');
        for (const c of ir.constraints) lines.push(`- ${c}`);
    }
    lines.push('');
    lines.push('## Acceptance criteria');
    const tests = ir.acceptance.filter(a => a.kind === 'test');
    const runs = ir.acceptance.filter(a => a.kind === 'run');
    if (tests.length) {
        lines.push('Behavioral checks that must hold after the change:');
        for (const t of tests) lines.push(`- ${t.value}`);
    }
    if (runs.length) {
        lines.push('');
        lines.push('Commands that must exit with code 0:');
        for (const r of runs) lines.push(`- \`${r.value}\``);
    }
    if (ir.rollback) {
        lines.push('');
        lines.push('## Rollback');
        lines.push(ir.rollback === 'revert'
            ? 'On failure, revert all changes (git revert / discard the branch).'
            : 'On failure, stop and wait for manual intervention. Do not attempt automatic repair beyond the acceptance loop.');
    }
    lines.push('');
    lines.push('---');
    lines.push('Generated by vibe-lang from a `change` declaration. The plan.json next to this file is the source of truth; run `vibe verify` against it after making changes.');
    lines.push('');
    return lines.join('\n');
}
