import type { ComponentIR, EntityIR, ProjectIR, UiElementIR } from '../ir/ir.js';

/** Convert "/images/{product.slug}.jpg" into a JSX template literal. */
function interpolate(str: string): string {
    const tpl = str.replace(/\{([a-zA-Z_][\w.]*)\}/g, '${$1}');
    return tpl.includes('${') ? `{\`${tpl}\`}` : JSON.stringify(str);
}

function refExpr(path: string[]): string {
    return path.join('.');
}

/** Value rendered as JSX child content (text between tags). */
function valueJsx(v: UiElementIR['value']): string {
    if (v.type === 'ref') return `{${refExpr(v.path)}}`;
    if (/\{[a-zA-Z_]/.test(v.value)) return interpolate(v.value);
    // plain text: escape JSX-significant characters, emit without quotes
    return v.value.replace(/[{}<>]/g, c => `{'${c}'}`);
}

function altExpr(ir: ProjectIR, comp: ComponentIR): string {
    // a11y lowering: derive alt text from the first human-readable string
    // field (title/name) of the first entity param, if accessibility is set.
    if (!ir.vibe.accessibility) return '""';
    const param = comp.params[0];
    const entity = ir.schema.find(e => e.name === param.entity);
    const field = entity?.fields.find(f =>
        (f.type === 'string' || f.type === 'text') && ['title', 'name', 'label'].includes(f.name)
    );
    return field ? `{${param.name}.${field.name}}` : '""';
}

function elementJsx(ir: ProjectIR, comp: ComponentIR, el: UiElementIR): string {
    switch (el.kind) {
        case 'image': {
            const src = el.value.type === 'string' ? interpolate(el.value.value) : `{${refExpr(el.value.path)}}`;
            return `      <img className="vibe-image" src=${src} alt=${altExpr(ir, comp)} />`;
        }
        case 'heading':
            return `      <h3 className="vibe-heading">${valueJsx(el.value)}</h3>`;
        case 'price': {
            // Decimal values are objects at runtime; stringify before rendering.
            const inner = el.value.type === 'ref' ? `{String(${refExpr(el.value.path)})}` : valueJsx(el.value);
            return `      <p className="vibe-price">${inner}</p>`;
        }
        case 'text':
            return `      <p className="vibe-text">${valueJsx(el.value)}</p>`;
        case 'button':
            return `      <button className="vibe-button" type="button">${valueJsx(el.value)}</button>`;
    }
}

export function generateComponent(ir: ProjectIR, comp: ComponentIR): string {
    const entityImports = [...new Set(comp.params.map(p => p.entity))].join(', ');
    const props = comp.params.map(p => `${p.name}: ${p.entity}`).join('; ');
    const args = comp.params.map(p => p.name).join(', ');

    return `// Generated by vibe-lang from \`component ${comp.name}\`. DO NOT EDIT.
import type { ${entityImports} } from '@prisma/client';

export function ${comp.name}({ ${args} }: { ${props} }) {
  return (
    <div className="vibe-card">
${comp.elements.map(el => elementJsx(ir, comp, el)).join('\n')}
    </div>
  );
}
`;
}
