import type { ProjectIR, RouteIR } from '../ir/ir.js';
import { queryFnName } from '../utils/names.js';

/** "/" -> "src/app/page.tsx", "/shop" -> "src/app/shop/page.tsx" */
export function pageFilePath(route: RouteIR): string {
    if (route.path === '/') return 'src/app/page.tsx';
    return `src/app${route.path}/page.tsx`;
}

function literalExpr(v: string | number | boolean): string {
    return typeof v === 'string' ? JSON.stringify(v) : String(v);
}

export function generatePage(ir: ProjectIR, route: RouteIR): string {
    const usedComponents = [...new Set(route.sections.map(s => s.component))];
    const usedQueryFns = route.loaders.map(l => {
        const [method, path] = l.api.split(' ');
        return queryFnName(method, path);
    });

    const imports = [
        ...usedComponents.map(c => `import { ${c} } from '@/components/${c}';`),
        usedQueryFns.length ? `import { ${[...new Set(usedQueryFns)].join(', ')} } from '@/lib/queries';` : ''
    ].filter(Boolean).join('\n');

    const loaderLines = route.loaders.map((l, i) => {
        const args = Object.entries(l.args)
            .map(([k, v]) => `${k}: ${literalExpr(v)}`)
            .join(', ');
        return `  const ${l.bind} = await ${usedQueryFns[i]}({ ${args} });`;
    }).join('\n');

    const heroJsx = route.hero
        ? `      <section className="vibe-hero">
${route.hero.title ? `        <h1 className="vibe-hero-title">${route.hero.title}</h1>\n` : ''}${route.hero.cta ? `        <a className="vibe-button" href="#${route.sections[0]?.name.toLowerCase() ?? 'main'}">${route.hero.cta}</a>\n` : ''}      </section>`
        : '';

    const sectionJsx = route.sections.map(s => {
        // key = primary key of the entity behind the component's first param
        const comp = ir.components.find(c => c.name === s.component);
        const param = comp?.params[0];
        const entity = ir.schema.find(e => e.name === param?.entity);
        const pk = entity?.fields.find(f => f.primaryKey)?.name ?? 'id';
        return `      <section id="${s.name.toLowerCase()}" className="vibe-grid">
        {${s.binding}.map(item => (
          <${s.component} key={item.${pk}} ${param?.name ?? 'item'}={item} />
        ))}
      </section>`;
    }).join('\n');

    return `// Generated by vibe-lang from \`page ${route.name} "${route.path}"\`. DO NOT EDIT.
${imports}

export default async function ${route.name}Page() {
${loaderLines}

  return (
    <main className="vibe-main">
${[heroJsx, sectionJsx].filter(Boolean).join('\n')}
    </main>
  );
}
`;
}
