import type { EntityField, EntityIR, ProjectIR } from '../ir/ir.js';

const PRISMA_TYPES: Record<EntityField['type'], string> = {
    uuid: 'String',
    string: 'String',
    text: 'String',
    int: 'Int',
    float: 'Float',
    decimal: 'Decimal',
    boolean: 'Boolean',
    datetime: 'DateTime'
};

function fieldLine(f: EntityField): string {
    const attrs: string[] = [];
    if (f.primaryKey) attrs.push('@id');
    if (f.unique) attrs.push('@unique');
    if (f.defaultFn === 'uuid') attrs.push('@default(uuid())');
    else if (f.defaultFn === 'now') attrs.push('@default(now())');
    else if (f.default !== undefined) {
        const v = typeof f.default === 'string' ? JSON.stringify(f.default) : String(f.default);
        attrs.push(`@default(${v})`);
    }
    return `  ${f.name} ${PRISMA_TYPES[f.type]}${attrs.length ? ' ' + attrs.join(' ') : ''}`;
}

function modelBlock(e: EntityIR): string {
    return `model ${e.name} {\n${e.fields.map(fieldLine).join('\n')}\n}`;
}

export function generatePrismaSchema(ir: ProjectIR): string {
    return `// Generated by vibe-lang from app ${ir.meta.name}. DO NOT EDIT.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${ir.schema.map(modelBlock).join('\n\n')}
`;
}
