import type { ApiIR, EntityIR, ProjectIR, QueryParamIR } from '../ir/ir.js';
import { camelCase, queryFnName } from '../utils/names.js';

function tsType(t: QueryParamIR['type']): string {
    switch (t) {
        case 'int': case 'float': case 'decimal': return 'number';
        case 'boolean': return 'boolean';
        default: return 'string';
    }
}

function entityOf(ir: ProjectIR, name: string): EntityIR {
    const e = ir.schema.find(s => s.name === name);
    if (!e) throw new Error(`unknown entity ${name}`);
    return e;
}

/**
 * Deterministic lowering conventions for query params:
 *   - `limit` (int)  -> prisma `take`
 *   - `q` (string)   -> case-insensitive OR-contains over the entity's
 *                       non-unique string fields
 *   - any param whose name matches an entity field -> equality filter
 * Ordering: first datetime field descending, if any.
 */
export function generateQueryFn(ir: ProjectIR, api: ApiIR): string {
    const entity = entityOf(ir, api.returns.entity);
    const fn = queryFnName(api.method, api.path);
    const model = camelCase(entity.name);

    const paramFields = api.query.map(p => {
        const opt = p.optional || p.default !== undefined ? '?' : '';
        return `${p.name}${opt}: ${tsType(p.type)}`;
    });
    const paramsType = paramFields.length ? `{ ${paramFields.join('; ')} }` : 'Record<string, never>';

    const whereParts: string[] = [];
    const searchableFields = entity.fields.filter(
        f => (f.type === 'string' || f.type === 'text') && !f.primaryKey && !f.unique
    );
    for (const p of api.query) {
        if (p.name === 'limit') continue;
        if (p.name === 'q' && searchableFields.length > 0) {
            const ors = searchableFields
                .map(f => `{ ${f.name}: { contains: params.q, mode: 'insensitive' as const } }`)
                .join(', ');
            whereParts.push(`...(params.q ? { OR: [${ors}] } : {})`);
        } else if (entity.fields.some(f => f.name === p.name)) {
            whereParts.push(`...(params.${p.name} !== undefined ? { ${p.name}: params.${p.name} } : {})`);
        }
    }

    const limitParam = api.query.find(p => p.name === 'limit');
    const takeExpr = limitParam
        ? `params.limit ?? ${typeof limitParam.default === 'number' ? limitParam.default : 20}`
        : undefined;

    const orderField = entity.fields.find(f => f.type === 'datetime');

    const opts: string[] = [];
    if (whereParts.length) opts.push(`    where: {\n      ${whereParts.join(',\n      ')}\n    }`);
    if (api.returns.many && takeExpr) opts.push(`    take: ${takeExpr}`);
    if (api.returns.many && orderField) opts.push(`    orderBy: { ${orderField.name}: 'desc' }`);

    const call = api.returns.many ? 'findMany' : 'findFirst';
    const body = opts.length
        ? `prisma.${model}.${call}({\n${opts.join(',\n')}\n  })`
        : `prisma.${model}.${call}()`;

    return `export async function ${fn}(params: ${paramsType}) {
  return ${body};
}`;
}

export function generateQueriesFile(ir: ProjectIR): string {
    return `// Generated by vibe-lang. DO NOT EDIT.
import { prisma } from './db';

${ir.apis.map(api => generateQueryFn(ir, api)).join('\n\n')}
`;
}
