import type { ProjectIR } from '../ir/ir.js';
import { kebabCase } from '../utils/names.js';

export function generateAppPackageJson(ir: ProjectIR): string {
    return JSON.stringify({
        name: kebabCase(ir.meta.name),
        version: ir.meta.version,
        private: true,
        scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
            'db:push': 'prisma db push',
            'db:generate': 'prisma generate'
        },
        dependencies: {
            '@prisma/client': '^6.0.0',
            next: '^15.0.0',
            react: '^19.0.0',
            'react-dom': '^19.0.0',
            zod: '^4.0.0'
        },
        devDependencies: {
            '@types/node': '^22.0.0',
            '@types/react': '^19.0.0',
            '@types/react-dom': '^19.0.0',
            prisma: '^6.0.0',
            typescript: '^5.6.0'
        }
    }, null, 2) + '\n';
}

export function generateAppTsconfig(): string {
    return JSON.stringify({
        compilerOptions: {
            target: 'ES2022',
            lib: ['dom', 'dom.iterable', 'esnext'],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
            paths: { '@/*': ['./src/*'] }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
    }, null, 2) + '\n';
}

export function generateDbClient(): string {
    return `// Generated by vibe-lang. DO NOT EDIT.
import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
`;
}

export function generateLayout(ir: ProjectIR): string {
    const description = ir.vibe.brandKeywords.length
        ? ir.vibe.brandKeywords.join(' ')
        : ir.meta.name;
    return `// Generated by vibe-lang. DO NOT EDIT.
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${ir.meta.name}',
  description: '${description}'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

/**
 * vibe/style lowering into CSS:
 *   - every style token becomes a CSS variable (dots -> dashes)
 *   - density token maps to a spacing scale
 *   - motion token maps to transition durations
 */
export function generateGlobalsCss(ir: ProjectIR): string {
    const tokens = ir.designSystem.tokens;
    const vars: string[] = [];
    for (const [key, value] of Object.entries(tokens)) {
        const cssName = '--' + key.replace(/\./g, '-');
        const cssValue = typeof value === 'number' ? `${value}px` : String(value);
        if (key === 'density') {
            const spacing = value === 'compact' ? '0.5rem' : value === 'cozy' ? '0.75rem' : '1rem';
            vars.push(`  --spacing: ${spacing};`);
        } else if (key === 'motion') {
            const duration = value === 'none' ? '0ms' : value === 'subtle' ? '150ms' : '300ms';
            vars.push(`  --motion-duration: ${duration};`);
        } else {
            vars.push(`  ${cssName}: ${cssValue};`);
        }
    }

    return `/* Generated by vibe-lang from the style block. DO NOT EDIT. */
:root {
${vars.join('\n')}
}

* { box-sizing: border-box; }

body {
  margin: 0;
  font-family: ui-sans-serif, system-ui, sans-serif;
  color: #1a1a1a;
}

.vibe-main { padding: calc(var(--spacing, 1rem) * 2); display: grid; gap: calc(var(--spacing, 1rem) * 2.5); }
.vibe-hero { max-width: 56rem; display: grid; gap: var(--spacing, 1rem); justify-items: start; }
.vibe-hero-title { font-size: 2.25rem; font-weight: 600; margin: 0; }
.vibe-grid { display: grid; gap: calc(var(--spacing, 1rem) * 1.5); grid-template-columns: repeat(auto-fill, minmax(14rem, 1fr)); }
.vibe-card { display: grid; gap: calc(var(--spacing, 1rem) * 0.5); padding: var(--spacing, 1rem); border: 1px solid #e5e5e5; border-radius: var(--radius-md, 8px); }
.vibe-image { width: 100%; aspect-ratio: 4 / 3; object-fit: cover; border-radius: calc(var(--radius-md, 8px) - 2px); background: #f4f4f4; }
.vibe-heading { margin: 0; font-size: 1rem; font-weight: 600; }
.vibe-price { margin: 0; color: #555; }
.vibe-text { margin: 0; }
.vibe-button {
  display: inline-flex;
  padding: calc(var(--spacing, 1rem) * 0.5) var(--spacing, 1rem);
  border: none;
  border-radius: var(--radius-md, 8px);
  background: var(--color-primary, #1a1a1a);
  color: #fff;
  font: inherit;
  text-decoration: none;
  cursor: pointer;
  transition: opacity var(--motion-duration, 150ms) ease;
}
.vibe-button:hover { opacity: 0.85; }
`;
}

/** Performance budgets and security posture become CI-consumable metadata. */
export function generateBudgetsJson(ir: ProjectIR): string {
    return JSON.stringify({
        performanceBudgets: ir.vibe.performanceBudgets,
        accessibility: ir.vibe.accessibility ?? null,
        securityProfile: ir.vibe.securityProfile,
        uxPriorities: ir.vibe.uxPriorities
    }, null, 2) + '\n';
}

export function generateGitignore(): string {
    return `node_modules/
.next/
.env
next-env.d.ts
`;
}

export function generateEnvExample(): string {
    return `DATABASE_URL="postgresql://user:password@localhost:5432/app"
`;
}
